const menusy = () => { 
	return `       
┏━━❉ *About User* ❉━━━┓
┣⊱*nama* : ${pushname}
┣⊱*bot* : Syzu_
┣⊱*Version* : 2.0.0
┏━━❉ *Cradits* ❉━━━┓
┣⊱Syzu_
┣⊱https://youtube.com/channel/UCk1pJSa8ICKOyzKLlFvOgUA
┣⊱AGAN TUTORIAL
┣⊱ https://youtube.com/c/AGANTUTORIAL
┗━━━━━━━━━━━━━━━━
┣⊱*${prefix}sticker (jika video max. 9det)* 
┣⊱*${prefix}shadow*
┣⊱*${prefix}cup*
┣⊱*${prefix}cup1*
┣⊱*${prefix}googlesearch*
┣⊱*${prefix}smoke*
┣⊱*${prefix}burnpaper*
┣⊱*${prefix}lovemessage*
┣⊱*${prefix}undergrass*
┣⊱*${prefix}itxt*
┣⊱*${prefix}attp*
┣⊱*${prefix}love*
┣⊱*${prefix}coffe*
┣⊱*${prefix}woodheart*
┣⊱*${prefix}flowerheart*
┣⊱*${prefix}woodenboard*
┣⊱*${prefix}darkneon*
┣⊱*${prefix}candlemug*
┣⊱*${prefix}lovemsg*
┣⊱*${prefix}mugflower*
┣⊱*${prefix}narutobanner*
┣⊱*${prefix}paperonglass*
┣⊱*${prefix}romancetext*
┣⊱*${prefix}shadowtext*
┣⊱*${prefix}coffecup*
┣⊱*${prefix}glowingneon*
┣⊱*${prefix}underwater*
┣⊱*${prefix}hpotter*
┣⊱*${prefix}woodblock*
┣⊱*${prefix}summer3d*
┣⊱*${prefix}tahta*
┣⊱*${prefix}wolfmetal*
┣⊱*${prefix}nature3d*
┣⊱*${prefix}underwater*
┣⊱*${prefix}golderrose*
┣⊱*${prefix}summernature*
┣⊱*${prefix}letterleaves*
┣⊱*${prefix}glowingneon*
┣⊱*${prefix}fallleaves*
┣⊱*${prefix}flamming*
┣⊱*${prefix}harrypotter*
┣⊱*${prefix}carvedwood*
┣⊱*${prefix}wetglass*
┣⊱*${prefix}multicolor3d*
┣⊱*${prefix}watercolor*
┣⊱*${prefix}luxurygold*
┣⊱*${prefix}galaxywallpaper*
┣⊱*${prefix}lighttext*
┣⊱*${prefix}beautifulflower*
┣⊱*${prefix}puppycute*
┣⊱*${prefix}royaltext*
┣⊱*${prefix}heartshaped*
┣⊱*${prefix}birthdaycake*
┣⊱*${prefix}galaxystyle
┣⊱*${prefix}hologram3d*
┣⊱*${prefix}glossychrome*
┣⊱*${prefix}greenbush*
┣⊱*${prefix}metallogo*
┣⊱*${prefix}noeltext*
┣⊱*${prefix}glittergold*
┣⊱*${prefix}textcake*
┣⊱*${prefix}starsnight* 
┣⊱*${prefix}wooden3d*
┣⊱*${prefix}textbyname*
┣⊱*${prefix}writegalacy*
┣⊱*${prefix}galaxybat*
┣⊱*${prefix}snow3d*
┣⊱*${prefix}birthdayday*
┣⊱*${prefix}freefire*
┣⊱*${prefix}kuncitext*
┣⊱*${prefix}textdaun* 
┣⊱*${prefix}nulis*
┣⊱*${prefix}silktext*
┣⊱*${prefix}makequote*
┣⊱*${prefix}toimg*
┣⊱*${prefix}ocr*
┣⊱*${prefix}galaxstyle*
┣⊱*${prefix}jokerlogo*
┣⊱*${prefix}toxic*
┣⊱*${prefix}bloodfrosted*
┣⊱*${prefix}hororblood*
┣⊱*${prefix}halloween*
┣⊱*${prefix}firework*
┣⊱*${prefix}glitch*
┣⊱*${prefix}blackpink*
┣⊱*${prefix}goldplay*
┣⊱*${prefix}hologram*
┣⊱*${prefix}textbyname*
┣⊱*${prefix}herrypoter*
┣⊱*${prefix}metallogo*
┣⊱*${prefix}ttp*
┣⊱*${prefix}thunder*
┣⊱*${prefix}bokeh*
┣⊱*${prefix}strawberry*
┣⊱*${prefix}metaldark*
┣⊱*${prefix}kuncitext*
┣⊱*${prefix}textdaun*
┣⊱*${prefix}nulis*
┣⊱*${prefix}silktext*
┣⊱*${prefix}makequote*
┣⊱*${prefix}toimg*
┣⊱*${prefix}ocr*
┣⊱*${prefix}galaxstyle*
┣⊱*${prefix}jokerlogo*
┣⊱*${prefix}toxic*
┣⊱*${prefix}triggered*
┣⊱*${prefix}gtav*
┣⊱*${prefix}nigthbeach*
┣⊱*${prefix}laptop*
┣⊱*${prefix}linephoto*
┣⊱*${prefix}raindrop*
┣⊱*${prefix}sketch*
┣⊱*${prefix}wanted*
┣⊱*${prefix}crossgun*
┣⊱*${prefix}bloodfrosted*
┣⊱*${prefix}hororblood*
┣⊱*${prefix}halloween*
┣⊱*${prefix}firework*
┣⊱*${prefix}blackpink*
┣⊱*${prefix}goldplay*
┣⊱*${prefix}hologram*
┣⊱*${prefix}textbyname*
┣⊱*${prefix}herrypoter*
┣⊱*${prefix}imagetext*
┣⊱*${prefix}greenneon*
┣⊱*${prefix}metallogo*
┣⊱*${prefix}spamcall*
┣⊱*${prefix}spamtext*
┣⊱*${prefix}mining*
┣⊱*${prefix}playstore*
┣⊱*${prefix}bisakah*
┣⊱*${prefix}kapankah*
┣⊱*${prefix}apakah*
┣⊱*${prefix}rate*
┣⊱*${prefix}truth*
┣⊱*${prefix}dare*
┣⊱*${prefix}hobby*
┣⊱*${prefix}memeindo*
┣⊱*${prefix}darkjoke*
┣⊱*${prefix}cerpen*
┣⊱*${prefix}quotesimage*
┣⊱*${prefix}fitnah*
┣⊱*${prefix}pasangan*
┣⊱*${prefix}ntahlah*
┣⊱*${prefix}slap*
┣⊱*${prefix}quotesmotivasi*
┣⊱*${prefix}quotessehat*
┣⊱*${prefix}quotescinta*
┣⊱*${prefix}hemkel*
┣⊱*${prefix}quotes2*
┣⊱*${prefix}katadoi*
┣⊱*${prefix}katakatadilan*
┣⊱*${prefix}qoutes*
┣⊱*${prefix}caklontong*
┣⊱*${prefix}family100*
┣⊱*${prefix}tebakgambar*
┣⊱*${prefix}kbbi*
┣⊱*${prefix}dadu*
┣⊱*${prefix}artinama*
┣⊱*${prefix}animesaran*
┣⊱*${prefix}animesaran2*
┣⊱*${prefix}husbu2*
┣⊱*${prefix}anime*
┣⊱*${prefix}wallpaperanime*
┣⊱*${prefix}trap* 
┣⊱*${prefix}baka2*
┣⊱*${prefix}wallpapernime*
┣⊱*${prefix}animefanart*
┣⊱*${prefix}megumin*
┣⊱*${prefix}shinobu*
┣⊱*${prefix}baka*
┣⊱*${prefix}eroyuri*
┣⊱*${prefix}happy*
┣⊱*${prefix}dance*
┣⊱*${prefix}neko3*
┣⊱*${prefix}smile*
┣⊱*${prefix}wallpaper*
┣⊱*${prefix}slapnime*
┣⊱*${prefix}shota*
┣⊱*${prefix}sagiri*
┣⊱*${prefix}femdom*
┣⊱*${prefix}waifukawai*
┣⊱*${prefix}kuni*
┣⊱*${prefix}nsfwloli3*
┣⊱*${prefix}kitsune*
┣⊱*${prefix}yuri*
┣⊱*${prefix}yaoi*
┣⊱*${prefix}wancak*
┣⊱*${prefix}quotesnime*
┣⊱*${prefix}waifu2*
┣⊱*${prefix}bj* (udh work)
┣⊱*${prefix}ram*
┣⊱*${prefix}pictlolicon*
┣⊱*${prefix}pictneko*
┣⊱*${prefix}testwaifu*
┣⊱*${prefix}nsfw_avatar*
┣⊱*${prefix}senku*
┣⊱*${prefix}pictwaifu*
┣⊱*${prefix}kurumi2*
┣⊱*${prefix}nakanomiku*
┣⊱*${prefix}wibu*
┣⊱*${prefix}wibu2*
┣⊱*${prefix}boruto*
┣⊱*${prefix}rize*
┣⊱*${prefix}kaneki*
┣⊱*${prefix}kemonomimi*
┣⊱*${prefix}holo*
┣⊱*${prefix}naruto*
┣⊱*${prefix}amv*
┣⊱*${prefix}minato*                                                                          
┣⊱*${prefix}tagall*
┣⊱*${prefix}gecg*
┣⊱*${prefix}avatar*
┣⊱*${prefix}miku*
┣⊱*${prefix}kurumi*
┣⊱*${prefix}hinata*
┣⊱*${prefix}sasuke*
┣⊱*${prefix}sakura*
┣⊱*${prefix}akura*
┣⊱*${prefix}itori*
┣⊱*${prefix}touka*
┣⊱*${prefix}rem*
┣⊱*${prefix}chika*
┣⊱*${prefix}quran*
┣⊱*${prefix}quotesislami*
┣⊱*${prefix}listsurah*
┣⊱*${prefix}beritahoax*
┣⊱*${prefix}brainly*
┣⊱*${prefix}pinterest*
┣⊱*${prefix}husbu*
┣⊱*${prefix}waifu2*
┣⊱*${prefix}waifu*
┣⊱*${prefix}loli*
┣⊱*${prefix}loli2*
┣⊱*${prefix}neko*
┣⊱*${prefix}neko2*
┣⊱*${prefix}nekonime*
┣⊱*${prefix}randomanime*
┣⊱*${prefix}randomhusbu*
┣⊱*${prefix}randomcyberspace*
┣⊱*${prefix}randomexo*
┣⊱*${prefix}blackpink*
┣⊱*${prefix}randomgame*
┣⊱*${prefix}randommountain*
┣⊱*${prefix}randomloli*
┣⊱*${prefix}randomprogramer*
┣⊱*${prefix}meme*
┣⊱*${prefix}memeindo*
┣⊱*${prefix}tts*
┣⊱*${prefix}play*
┣⊱*${prefix}lirik*
┣⊱*${prefix}ssweb*
┣⊱*${prefix}map*
┣⊱*${prefix}stalkig*
┣⊱*${prefix}afk*
┣⊱*${prefix}unafk*
┣⊱*${prefix}asupan*
┣⊱*${prefix}limit*
┣⊱*${prefix}buylimit*
┣⊱*${prefix}dompet*
┣⊱*${prefix}pokemon*
┣⊱*${prefix}anjing*
┣⊱*${prefix}nsfwloli*
┣⊱*${prefix}nsfwneko*
┣⊱*${prefix}solo*
┣⊱*${prefix}nsfwtrap*
┣⊱*${prefix}nsfwpussy*
┣⊱*${prefix}nsfwyuri*
┣⊱*${prefix}ero*
┣⊱*${prefix}nsfwloli2*
┣⊱*${prefix}sideoppai*
┣⊱*${prefix}nsfwwaifu*
┣⊱*${prefix}ecchi*
┣⊱*${prefix}nekopoi* <judul>
┣⊱*${prefix}hidetag*
┣⊱*${prefix}del*
┣⊱*${prefix}grouplist*
┣⊱*${prefix}level*
┣⊱*${prefix}leaderboard*
┣⊱*${prefix}linkgc*
┣⊱*${prefix}tagall*
┣⊱*${prefix}setpp*
┣⊱*${prefix}add*
┣⊱*${prefix}kick*
┣⊱*${prefix}setname*
┣⊱*${prefix}setdesc*
┣⊱*${prefix}demote*
┣⊱*${prefix}promote*
┣⊱*${prefix}listadmin*
┣⊱*${prefix}closegc*
┣⊱*${prefix}opengc*
┣⊱*${prefix}leveling*
┣⊱*${prefix}nsfw* [1/0]
┣⊱*${prefix}simih* [1/0]
┣⊱*${prefix}welcome* [1/0]
┣⊱*${prefix}antilinkgrup* [1/0]
┣⊱*${prefix}bc*
┣⊱*${prefix}bcgc*
┣⊱*${prefix}kickall*
┣⊱*${prefix}setreply*
┣⊱*${prefix}setprefix*
┣⊱*${prefix}clearall*
┣⊱*${prefix}ban*
┣⊱*${prefix}unban*
┣⊱*${prefix}block*
┣⊱*${prefix}unblock*
┣⊱*${prefix}setmemberlimit*
┣⊱*${prefix}addbadword* <teks>
┣⊱*${prefix}listbadword*
┣⊱*${prefix}nobadword*
┣⊱*${prefix}listblock*
┣⊱*${prefix}leave*
┣⊱*${prefix}event* [1/0]
┣⊱*${prefix}clone*
┣⊱${prefix}setppbot
┗━━━━━━━━━━━━━━━━`
}

exports.menusy = menusy
